mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs-concat', '6.1.0'
mod 'puppetlabs-stdlib', '6.2.0'
mod 'puppetlabs-translate', '2.1.0'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.9.0'
