mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.9.0'
mod 'theforeman-foreman', '13.1.0'
mod 'puppetlabs-apache', '5.3.0'
mod 'puppetlabs-postgresql', '6.3.0'
mod 'puppet-extlib', '4.1.0'
